version: "2"
services:
  app:
    container_name: APPNAME
    restart: always
    build: .
    ports:
      - "8081:8081"
    links:
      - mongo
    environment:
      - NODE_ENV=development
      - DBURL=mongodb://mongo/appDb
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"